diary/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.Top.as_view(), name='top'),
    path('create/', views.Create.as_view(), name='create'),
    path('list/', views.List.as_view(), name='list'),
    path('<int:pk>/', views.Detail.as_view(), name='detail'),
    path('<int:pk>/update/', views.Update.as_view(), name='update'),
    path('<int:pk>/delete/', views.Delete.as_view(), name='delete'),
]

mydiary/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('diary/', include('diary.urls')),
    path('admin/', admin.site.urls),
]

diary/models.py
from django.db import models
from django.utils import timezone


class Post(models.Model):
    title = models.CharField(max_length=256)
    datetime = models.DateTimeField(auto_now_add=True)
    text = models.TextField()

diary/views.py
from django.shortcuts import render
from django.contrib import messages
from django.urls import reverse_lazy
from django.views.generic import (
    TemplateView,
    CreateView,
    ListView,
    DetailView,
    DeleteView,
    UpdateView,
)
from . import models


class Top(TemplateView):
    template_name = 'diary/top.html'


class Create(CreateView):
    template_name = 'diary/form.html'
    model = models.Post
    fields = ('title', 'text')
    success_url = '/diary/list/'

    def form_valid(self, form):
        messages.success(self.request, 'Notice : created post')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.warning(self.request, 'Notice : could not created post')
        return super().form_invalid(form)


class List(ListView):
    template_name = 'diary/list.html'
    model = models.Post
    

class Detail(DetailView):
    template_name = 'diary/detail.html'
    model = models.Post


class Update(UpdateView):
    template_name = 'diary/form.html'
    model = models.Post
    fields = ('title', 'text')

    def get_success_url(self):
        return reverse_lazy('detail', kwargs={'pk':self.kwargs['pk']})

    def form_valid(self, form):
        messages.success(self.request, 'Notice : updated post')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.warning(self.request, 'Notice : could not updated post')
        return super().form_invalid(form)



class Delete(DeleteView):
    template_name = 'diary/delete.html'
    model = models.Post
    success_url = '/diary/list/'

diary/templates/diary/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>My Diary</title>
</head>
<body>

    <h1><a href="{% url 'list' %}">My Diary</a></h1>
    {% block body %}
    {% endblock %}
</body>
</html>

diary/templates/diary/create.html
{% extends "diary/base.html" %}

{% block body %}

<h1>create new post</h1>

<form method='post'>
    {% csrf_token %}
    <table>
        {{ form }}
    </table>
    <button>save</button>
</form>

{% endblock %}

diary/templates/diary/delete.html
{% extends "diary/base.html" %}

{% block body %}

<strong><p>delete {{ post.title }} ?</p></strong>

<form method='post'>
    {% csrf_token %}
    <button>delete</button>
</form>

{% endblock %}

diary/templates/diary/detail.html
{% extends "diary/base.html" %}

{% block body %}

<h1>{{ post.title }}</h1>

<p>created date : {{ post.datetime }}</p>
<br>
<strong>text</strong>
<br>
<p>{{ post.text | linebreaksbr }}</p>

<p><a href="{% url 'update' post.pk %}">update</a></p>

<p><a href="{% url 'delete' post.pk %}">delete</a></p>

{% endblock %}

diary/templates/diary/form.html
{% extends "diary/base.html" %}

{% block body %}

<h1>create new post</h1>

<form method='post'>
    {% csrf_token %}
    <table>
        {{ form }}
    </table>
    <button>save</button>
</form>

{% endblock %}

diary/templates/diary/index.html
{% extends "diary/base.html" %}

{% block body %}

<h1>my diary</h1>

<a href="{% url 'list' %}">post list</a>

{% endblock %}

diary/templates/diary/list.html
{% extends "diary/base.html" %}

{% block body %}

<h1>Post list</h1>

{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <strong><li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li></strong>
    {% endfor %}
</ul>
{% endif %}

<p><a href="{% url 'create' %}">create new</a></p>

<ul>
    {% for post_list in object_list %}
    <li><a href="{% url 'detail' post_list.pk %}">{{ post_list.title }}</a></li>
    {% endfor %}
</ul>

{% endblock %}

diary/templates/diary/post_detail.html
{% extends "diary/base.html" %}

{% block body %}

<h1>{{ post.title }}</h1>

<p>created date : {{ post.datetime }}</p>

<p>{{ post.text }}</p>

{% endblock %}

diary/templates/diary/top.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>My Diary</title>
</head>
<body>

    <script type="text/javascript">
        function password(){
            var word = prompt("Please enter password");
            location.href = word;
        }
    </script>

    <h1>My Diary</h1>

    <input type="button" value="my diary" onclick="password();">

</body>
</html>